all: prog5-1 prog5-2 prog5-3 prog5-4 prog5-5
prog5-1: prog5-1.c apue.c
prog5-2: prog5-2.c apue.c
prog5-3: prog5-3.c apue.c
prog5-4: prog5-4.c apue.c
prog5-5: prog5-5.c apue.c
clean:
	- rm prog5-1 
	- rm prog5-2 
	- rm prog5-3
	- rm prog5-4
	- rm prog5-5
