all: hello_world prog7-2 prog7-3 prog7-6 prog7-8
hello_world: hello_world.c apue.c
prog7-2: prog7-2.c apue.c
prog7-3: prog7-3.c apue.c
prog7-6: prog7-6.c apue.c
prog7-8: prog7-8.c apue.c
clean:
	- rm hello_world
	- rm prog7-2
	- rm prog7-3
	- rm prog7-6
	- rm prog7-8
