all: ex02-09.pdf ex10-15.pdf ex16-33.pdf ex34.pdf ex35-54.pdf
ex02-09.pdf: ex02-09.tex
	xelatex $^
ex10-15.pdf: ex10-15.tex
	xelatex $^
ex16-33.pdf: ex16-33.tex
	xelatex $^
ex34.pdf: ex34.tex
	xelatex $^
	xelatex $^
ex35-54.pdf: ex35-54.tex
	xelatex $^
	xelatex $^
clean:
	rm *.pdf
	rm *.aux
	rm *.log
